### ISSUE TITLE
Blake3 doesn't work out of the box

### ISSUE THREAD

**Issue by aaronmondal** [TraceMachina/nativelink#566] opened 2023-12-21 02:41 UTC
See https://github.com/TraceMachina/nativelink/actions/runs/7283284527/job/19846935971?pr=565

We have config flags to set this, but things should automatically work with `--digest_function=blake3`.

**Comment by allada** [comment] 2023-12-22 04:57
Duplicate of https://github.com/TraceMachina/nativelink/issues/444

**Closed** 2023-12-22 04:57 UTC
Labels: bug, duplicate
