### ISSUE TITLE
Add Kubernetes Instructions to the Documentation App 

### ISSUE THREAD

**Issue by MarcusSorealheis** [TraceMachina/nativelink#593] opened 2024-01-05 19:21 UTC
We currently have [experimental K8s instruction](https://github.com/TraceMachina/nativelink/tree/main/deployment-examples/kubernetes#kubernetes-example)s in the repo. They should be labeled "experimental" as more customers offer feedback. These instructions should also be included in the Docs app because some people will find it easier to navigate and parse.

**Comment by aaronmondal** [comment] 2024-01-05 22:19
I believe the reason we flagged the Terraform examples as experimental was because we didn't have CI to prevent regressions. The K8s deployment runs in CI and is regression tested, so it would seem somewhat confusing to me if we marked it as experimental.

The docs certainly should contain all deployment readmes, regardless of stability. I'm not sure whether adding things to the docs manually all the time is the way to go though. We need infra to handle this automatically. I've created #594 to track this.

**Closed** 2024-01-08 02:33 UTC
Labels: documentation
